-- Milestone 3: auth, company, profile, company settings and audit foundation
-- This migration is intended to be applied once in the target Supabase project.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.companies (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL CHECK (length(trim(name)) > 0),
    legal_name text NULL,
    phone text NULL,
    email text NULL,
    tax_number text NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY,
    company_id uuid NOT NULL,
    full_name text NOT NULL CHECK (length(trim(full_name)) > 0),
    phone text NULL,
    role text NOT NULL CHECK (role IN ('admin', 'secretary', 'technician')),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT profiles_company_fk
        FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT,
    CONSTRAINT profiles_auth_fk
        FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.company_settings (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL UNIQUE,
    currency_code text NOT NULL DEFAULT 'TRY',
    locale_code text NOT NULL DEFAULT 'tr-TR',
    timezone text NOT NULL DEFAULT 'Europe/Istanbul',
    maintenance_reminder_days integer NOT NULL DEFAULT 15 CHECK (maintenance_reminder_days >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT company_settings_company_fk
        FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL,
    user_id uuid NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid NULL,
    old_values jsonb NULL,
    new_values jsonb NULL,
    metadata jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT audit_logs_company_fk
        FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT,
    CONSTRAINT audit_logs_user_fk
        FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_profiles_company_id ON public.profiles(company_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_is_active ON public.profiles(is_active);
CREATE INDEX IF NOT EXISTS idx_company_settings_company_id ON public.company_settings(company_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_company_id ON public.audit_logs(company_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON public.audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_type ON public.audit_logs(entity_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_id ON public.audit_logs(entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at_desc ON public.audit_logs(created_at DESC);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_companies_set_updated_at ON public.companies;
CREATE TRIGGER trg_companies_set_updated_at
BEFORE UPDATE ON public.companies
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_profiles_set_updated_at ON public.profiles;
CREATE TRIGGER trg_profiles_set_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_company_settings_set_updated_at ON public.company_settings;
CREATE TRIGGER trg_company_settings_set_updated_at
BEFORE UPDATE ON public.company_settings
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.current_user_company_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT company_id
  FROM public.profiles
  WHERE id = auth.uid() AND is_active = true
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT role
  FROM public.profiles
  WHERE id = auth.uid() AND is_active = true
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.is_current_user_active()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid() AND is_active = true
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(
    (SELECT role = 'admin' AND is_active = true FROM public.profiles WHERE id = auth.uid() LIMIT 1),
    false
  );
$$;

CREATE OR REPLACE FUNCTION public.is_secretary()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(
    (SELECT role = 'secretary' AND is_active = true FROM public.profiles WHERE id = auth.uid() LIMIT 1),
    false
  );
$$;

CREATE OR REPLACE FUNCTION public.is_technician()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(
    (SELECT role = 'technician' AND is_active = true FROM public.profiles WHERE id = auth.uid() LIMIT 1),
    false
  );
$$;

CREATE OR REPLACE FUNCTION public.enforce_profile_update_policy()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_user_id uuid := auth.uid();
  current_role text;
  current_company_id uuid;
  self_update boolean;
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required for profile updates.' USING ERRCODE = '42501';
  END IF;

  SELECT role, company_id
    INTO current_role, current_company_id
    FROM public.profiles
    WHERE id = current_user_id AND is_active = true
    LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active profile exists for the authenticated user.' USING ERRCODE = '42501';
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id OR NEW.company_id IS DISTINCT FROM OLD.company_id OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'Identity fields of a profile cannot be changed.' USING ERRCODE = '42501';
  END IF;

  self_update := (OLD.id = current_user_id);

  IF self_update THEN
    IF NEW.full_name IS NOT DISTINCT FROM OLD.full_name
       AND NEW.phone IS NOT DISTINCT FROM OLD.phone
       AND NEW.role IS NOT DISTINCT FROM OLD.role
       AND NEW.is_active IS NOT DISTINCT FROM OLD.is_active THEN
      RETURN NEW;
    END IF;

    IF NEW.role IS DISTINCT FROM OLD.role OR NEW.is_active IS DISTINCT FROM OLD.is_active THEN
      RAISE EXCEPTION 'You may only update your own full_name and phone.' USING ERRCODE = '42501';
    END IF;

    IF NEW.full_name IS DISTINCT FROM OLD.full_name OR NEW.phone IS DISTINCT FROM OLD.phone THEN
      RETURN NEW;
    END IF;

    RETURN NEW;
  END IF;

  IF current_role = 'admin' AND current_company_id = OLD.company_id THEN
    IF NEW.full_name IS NOT DISTINCT FROM OLD.full_name
       AND NEW.phone IS NOT DISTINCT FROM OLD.phone
       AND NEW.role IS NOT DISTINCT FROM OLD.role
       AND NEW.is_active IS NOT DISTINCT FROM OLD.is_active THEN
      RETURN NEW;
    END IF;

    IF NEW.full_name IS DISTINCT FROM OLD.full_name OR NEW.phone IS DISTINCT FROM OLD.phone OR NEW.role IS DISTINCT FROM OLD.role OR NEW.is_active IS DISTINCT FROM OLD.is_active THEN
      RETURN NEW;
    END IF;
  END IF;

  RAISE EXCEPTION 'You are not allowed to update this profile.' USING ERRCODE = '42501';
END;
$$;

REVOKE EXECUTE ON FUNCTION public.current_user_company_id() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_company_id() TO authenticated;

REVOKE EXECUTE ON FUNCTION public.current_user_role() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_role() TO authenticated;

REVOKE EXECUTE ON FUNCTION public.is_current_user_active() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_current_user_active() TO authenticated;

REVOKE EXECUTE ON FUNCTION public.is_admin() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

REVOKE EXECUTE ON FUNCTION public.is_secretary() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_secretary() TO authenticated;

REVOKE EXECUTE ON FUNCTION public.is_technician() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_technician() TO authenticated;

REVOKE EXECUTE ON FUNCTION public.enforce_profile_update_policy() FROM PUBLIC, anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS companies_select_own_company ON public.companies;
CREATE POLICY companies_select_own_company
ON public.companies
FOR SELECT
USING (
  is_active = true AND id = public.current_user_company_id()
);

-- Company activation is intentionally not client-editable here.
-- Activation and deactivation should be handled through a trusted server-side process.
DROP POLICY IF EXISTS companies_update_own_company ON public.companies;
CREATE POLICY companies_update_own_company
ON public.companies
FOR UPDATE
USING (
  public.is_admin() AND id = public.current_user_company_id()
)
WITH CHECK (
  public.is_admin() AND id = public.current_user_company_id() AND is_active = true
);

DROP POLICY IF EXISTS companies_no_insert ON public.companies;
CREATE POLICY companies_no_insert
ON public.companies
FOR INSERT
WITH CHECK (false);

DROP POLICY IF EXISTS companies_no_delete ON public.companies;
CREATE POLICY companies_no_delete
ON public.companies
FOR DELETE
USING (false);

DROP POLICY IF EXISTS profiles_select_own_profile ON public.profiles;
CREATE POLICY profiles_select_own_profile
ON public.profiles
FOR SELECT
USING (
  public.is_current_user_active() AND (
    id = auth.uid() OR (
      public.is_admin() AND company_id = public.current_user_company_id()
    )
  )
);

DROP POLICY IF EXISTS profiles_update_own_profile ON public.profiles;
CREATE POLICY profiles_update_own_profile
ON public.profiles
FOR UPDATE
USING (
  public.is_current_user_active() AND id = auth.uid()
)
WITH CHECK (
  public.is_current_user_active() AND id = auth.uid()
);

DROP POLICY IF EXISTS profiles_update_company_members ON public.profiles;
CREATE POLICY profiles_update_company_members
ON public.profiles
FOR UPDATE
USING (
  public.is_current_user_active() AND public.is_admin() AND company_id = public.current_user_company_id()
)
WITH CHECK (
  public.is_current_user_active() AND public.is_admin() AND company_id = public.current_user_company_id()
);

DROP POLICY IF EXISTS profiles_no_insert ON public.profiles;
CREATE POLICY profiles_no_insert
ON public.profiles
FOR INSERT
WITH CHECK (false);

DROP POLICY IF EXISTS profiles_no_delete ON public.profiles;
CREATE POLICY profiles_no_delete
ON public.profiles
FOR DELETE
USING (false);

DROP POLICY IF EXISTS company_settings_select_own ON public.company_settings;
CREATE POLICY company_settings_select_own
ON public.company_settings
FOR SELECT
USING (
  company_id = public.current_user_company_id() AND public.is_current_user_active()
);

DROP POLICY IF EXISTS company_settings_update_own ON public.company_settings;
CREATE POLICY company_settings_update_own
ON public.company_settings
FOR UPDATE
USING (
  public.is_admin() AND company_id = public.current_user_company_id()
)
WITH CHECK (
  public.is_admin() AND company_id = public.current_user_company_id()
);

DROP POLICY IF EXISTS company_settings_no_insert ON public.company_settings;
CREATE POLICY company_settings_no_insert
ON public.company_settings
FOR INSERT
WITH CHECK (false);

DROP POLICY IF EXISTS company_settings_no_delete ON public.company_settings;
CREATE POLICY company_settings_no_delete
ON public.company_settings
FOR DELETE
USING (false);

DROP POLICY IF EXISTS audit_logs_select_admin_company ON public.audit_logs;
CREATE POLICY audit_logs_select_admin_company
ON public.audit_logs
FOR SELECT
USING (
  public.is_admin() AND company_id = public.current_user_company_id()
);

DROP POLICY IF EXISTS audit_logs_no_write ON public.audit_logs;
CREATE POLICY audit_logs_no_write
ON public.audit_logs
FOR INSERT
WITH CHECK (false);

DROP POLICY IF EXISTS audit_logs_no_update ON public.audit_logs;
CREATE POLICY audit_logs_no_update
ON public.audit_logs
FOR UPDATE
USING (false)
WITH CHECK (false);

DROP POLICY IF EXISTS audit_logs_no_delete ON public.audit_logs;
CREATE POLICY audit_logs_no_delete
ON public.audit_logs
FOR DELETE
USING (false);

DROP TRIGGER IF EXISTS trg_profiles_enforce_update_policy ON public.profiles;
CREATE TRIGGER trg_profiles_enforce_update_policy
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.enforce_profile_update_policy();

